### ISSUE TITLE
Accounts - Billing information from F0116 Null on Account change

### ISSUE THREAD

**Issue by Hhopkins616** [ntnamericas/jde-to-sf-app#4]

**Comment by Hhopkins616** [comment]
In subqueries, current criteria is pulling in date and time from F0116. This is not needed in queries, just in the trigger

**Comment by ntn-mule** [comment]
Looking into this.

Issue identified for Account Number : 30059 > Billing Address not going through to SF. Too many date time queries on the SQL. Need Fine tuning.
